name: women_safety_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  firebase_auth: ^5.5.1
  firebase_auth_web: ^5.0.0
  google_sign_in: ^6.1.5
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_map_marker_popup: ^5.2.0
  firebase_storage: ^12.4.4
<<<<<<< HEAD
=======
  file_picker: ^8.0.0
>>>>>>> 1a12914624269ef82cfeec3aa2e93a577bf47461
  cupertino_icons: ^1.0.8

  geolocator: ^10.0.0
  geocoding: ^3.0.0
<<<<<<< HEAD
  url_launcher: ^6.3.1
=======
  image_picker: ^0.8.7+4
>>>>>>> 1a12914624269ef82cfeec3aa2e93a577bf47461

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^0.1.1+2

flutter:
  uses-material-design: true

