name: women_safety_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1r

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  firebase_auth: ^5.5.1
  firebase_auth_web: ^5.0.0
  google_sign_in: ^6.1.5
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
